# Site settings
title: "Typewriter"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://mismaelys.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "git"
    url: http://github.com/mismaelys
  - title: "rss"
    url: /feed.xml
